export const questionTypesMap = <Record<string, string>>{
  1: '单选题',
  2: '多选题',
  3: '判断题',
}

export const isEnabledMap = <Record<string, string>>{
  0: '禁用',
  1: '启用',
}

export const fileTypeMap = <Record<string, string>>{
  txt: 'text/plain',
  doc: 'application/msword',
  docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  xls: 'application/vnd.ms-excel',
  xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  ppt: 'application/vnd.ms-powerpoint',
  pptx: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  pdf: 'application/pdf',
  png: 'image/png',
  jpg: 'image/jpeg',
  jpeg: 'image/jpeg',
  gif: 'image/gif',
  bmp: 'image/bmp',
  svg: 'image/svg+xml',
  zip: 'application/zip',
  rar: 'application/x-rar-compressed',
  '7z': 'application/x-7z-compressed',
  tar: 'application/x-tar',
  gz: 'application/gzip',
  'tar.gz': 'application/gzip',
  'tar.bz2': 'application/x-bzip-compressed-tar',
  bz2: 'application/x-bzip-compressed',
  wav: 'audio/x-wav',
  mp3: 'audio/mpeg',
  ogg: 'audio/ogg',
  wma: 'audio/x-ms-wma',
  flac: 'audio/flac',
  aac: 'audio/aac',
  mp4: 'video/mp4',
  avi: 'video/x-msvideo',
  mov: 'video/quicktime',
  wmv: 'video/x-ms-wmv',
  flv: 'video/x-flv',
  mkv: 'video/x-matroska',
  webm: 'video/webm',
  swf: 'application/x-shockwave-flash',
  rtf: 'application/rtf',
  html: 'text/html',
  css: 'text/css',
  js: 'text/javascript',
  json: 'application/json',
  xml: 'application/xml',
  csv: 'text/csv',
  md: 'text/markdown',
  yml: 'text/yaml',
  yaml: 'text/yaml',
  toml: 'text/toml',
  ini: 'text/ini',
  conf: 'text/ini',
}

export const intPassword = '123456788'
